db.menu.insert([{
	_id: NumberLong(1),
	name : "Home",
	title: "Home",
	order: NumberInt(1),
	active: true,
	enabled: true,
	parentId:  null,
	definition: {
		url: "/home.html",
		component : "home",
	},
},
{
	_id: NumberLong(2),
	name: "AboutMe",
	title: "About Me",
	order: NumberInt(2),
	active: true,
	enabled: false,
	parentId: null,
	definition: {
		url: "/about-me.html",
		component: "aboutMe",
	},
},
{
	_id: NumberLong(3),
	name: "Utilities",
	title: "Utilities",
	order: NumberInt(3),
	parentId: null,
	active: false,
	enabled: false,
},
{
	_id: NumberLong(4),
	name: "ConvertHexToRgb",
	title: "Hexadecimal to RGB converter",
	order: NumberInt(1),
	parentId: NumberInt(3),
	active: true,
	enabled: false,
	definition: {
		url: "/hex-rgb-converter.html",
		component: "hexRgbConverter",
	},
},
{
	_id: NumberLong(8),
	name: "PickColors",
	title: "Pick colors from image",
	order: NumberInt(2),
	parentId: NumberInt(3),
	active: true,
	enabled: false,
	definition: {
		url: "/pick-colors.html",
		component: "pickColors",
	},
},
{
	_id: NumberLong(9),
	name: "FormatJson",
	title: "Json Formatter",
	order: NumberInt(3),
	parentId: NumberInt(3),
	active: true,
	enabled: false,
	definition: {
		url: "/format-json.html",
		component: "formatJson"
	},
},
{
	_id: NumberLong(10),
	name: "CharactersCount",
	title: "Count characters/words",
	order: NumberInt(4),
	parentId: NumberInt(3),
	active: true,
	enabled: false,
},
{
	_id: NumberLong(11),
	name: "Experiments",
	title: "Experiments",
	order: NumberInt(3),
	parentId: null,
	active: false,
	enabled: false,
},
{
	_id: NumberInt(12),
	name: "ImageFilters",
	title: "Image Filters",
	order: NumberInt(1),
	parentId: NumberInt(5),
	active: false,
	enabled: false,
}]);
